marketplace/project/conversation/urls.py
from django.urls import path

from . import views

app_name = 'conversation'

urlpatterns = [
    path('', views.inbox, name='inbox'),
    path('<int:pk>/', views.detail, name='detail'),
    path('new/<int:product_pk>/', views.new_conversation, name='new'),
]

marketplace/project/core/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required
from core.views import MainPage, SignUp, Login, Logout

app_name = 'core'

urlpatterns = [
    path('', MainPage.as_view(), name='mainpage'),
    path('signup/', SignUp.as_view(), name='signup'),
    path('login/', Login.as_view(), name='login'),
    path('logout/', Logout.as_view(), name='logout'),
]

marketplace/project/products/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required
from products.views import CreateProduct, ProductDetail, delete, edit, products


app_name = 'product'

urlpatterns = [
    path('', products, name='products'),
    path('create_product/', login_required(CreateProduct.as_view()), name='create_product'),
    path('<int:pk>/', ProductDetail.as_view(), name='detail'),
    path('<int:pk>/delete/', delete, name='delete'),
    path('<int:pk>/edit/', edit, name='edit'),
]

marketplace/project/project/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('core.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('inbox/', include('conversation.urls')),
    path('products/', include('products.urls', namespace='products'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

marketplace/project/products/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.
class Client(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    sales = models.IntegerField(default=0)
    purchases = models.IntegerField(default=0)


class Category(models.Model):
    name_cat = models.CharField(max_length=100)
    
    class Meta:
        ordering = ('name_cat',)
        verbose_name_plural = 'Категории'
    
    def __str__(self):
        return self.name_cat


class Product(models.Model):
    name_prod = models.CharField(max_length=100)
    description = models.TextField()
    price = models.IntegerField()
    is_sold = models.BooleanField(default=False)
    creater_date = models.DateField(auto_now_add=True)
    created_by = models.ForeignKey(User, related_name='products',  on_delete=models.CASCADE)
    category = models.ForeignKey(Category, related_name='products', on_delete=models.CASCADE)
    image = models.ImageField(upload_to='products/images', null=True)
    
    class Meta:
        verbose_name_plural = 'Товары'
    
    def __str__(self):
        return self.name_prod

class Basket(models.Model):
    client = models.ForeignKey(Client, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)

marketplace/project/products/forms.py
from django.forms import ModelForm
from .models import Client, Category, Product, Basket
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django import forms
from django.contrib.auth.models import User


INPUT_CLASSES = 'w-100 py-3 px-6 rounded-3'

class ProductForm(ModelForm):
    class Meta:
        model = Product
        fields = ('name_prod', 'description', 'price', 'category','image')
        widgets = { 
            'name_prod': forms.TextInput(attrs={"class": INPUT_CLASSES}),
            'description': forms.TextInput(attrs={"class": INPUT_CLASSES}),
            'price': forms.TextInput(attrs={"class": INPUT_CLASSES}),
            'category': forms.Select(attrs={"class": INPUT_CLASSES}),
            'image': forms.FileInput(attrs={"class": INPUT_CLASSES}),
        }
        
class EditProductForm(ModelForm):
    # captcha = CaptchaField(label='Введите текст с картинки', error_messages={'invalid':'Неправильный текст'}, generator='captcha.helpers.math_challenge')
    class Meta:
        model = Product
        fields = ('name_prod', 'description', 'price','image', 'is_sold')
        widgets = { 
            'name_prod': forms.TextInput(attrs={"class": INPUT_CLASSES}),
            'description': forms.TextInput(attrs={"class": INPUT_CLASSES}),
            'price': forms.TextInput(attrs={"class": INPUT_CLASSES}),
            'image': forms.FileInput(attrs={"class": INPUT_CLASSES}),
        }
        

marketplace/project/products/views.py
from urllib import request
from django.http import HttpRequest, HttpResponse, HttpResponseRedirect
from django.db.models import Q
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse, reverse_lazy
from .models import  Category, Client, Product, Basket
from .forms import EditProductForm, ProductForm
from django.views.generic import CreateView, ListView, View
from django.contrib.auth.decorators import login_required

    
def products(request):
    query = request.GET.get('query', '')
    category_id = request.GET.get('category', 0)
    categories = Category.objects.all()
    products = Product.objects.filter(is_sold=False)

    if category_id:
        products = products.filter(category_id=category_id)

    if query:
        products = products.filter(Q(name_prod__icontains=query) | Q(description__icontains=query))
    
    return render(request, 'product/products.html', {
        'products':products,
        'query': query, 
        'categories':categories,
        'category_id':category_id
        })
    
class ProductDetail(View):
    def get(self, request, *args, **kwargs):
        product = get_object_or_404(Product, pk=kwargs['pk'])
        related_products = Product.objects.filter(category=product.category, is_sold=False).exclude(pk=kwargs['pk'])[0:3]
        context = {
            'product': product,
            'related_products': related_products 
            }
        return render(request, 'product/product_detail.html', context)

class CreateProduct(CreateView):
    model = Product
    form_class = ProductForm
    template_name = 'product/create_product.html'
    success_url = reverse_lazy('core:mainpage')
    
    def form_valid(self, form):
        # Получите текущего пользователя
        current_user = self.request.user

        # Создайте экземпляр модели Product с commit=False
        product = form.save(commit=False)

        # Измените поле created_by на текущего пользователя
        product.created_by = current_user

        # Сохраните экземпляр Product в базе данных
        product.save()
        self.success_url = reverse('core:mainpage')

        return super().form_valid(form)
    
@login_required
def edit(request, pk):
    item = get_object_or_404(Product, pk=pk, created_by=request.user)

    if request.method == 'POST':
        form = EditProductForm(request.POST, request.FILES, instance=item)

        if form.is_valid():
            form.save()

            return redirect('product:detail', pk=item.id)
    else:
        form = EditProductForm(instance=item)

    return render(request, 'product/create_product.html', {
        'form': form,
        'title': 'Edit product',
    })


def add_to_basket(request, product_id):
    """
    Add a product to the user's basket.

    Args:
        request (HttpRequest): The HTTP request object.
        product_id (int): The ID of the product to be added.

    Returns:
        HttpResponseRedirect: Redirects the user to the 'basket' page if the user is authenticated,
        otherwise redirects the user to the 'login' page.
    """
    if request.user.is_authenticated:
        Basket.objects.create(buyer_id = request.user.id, product_id = product_id)
        return HttpResponseRedirect(reverse('basket'))
    return HttpResponseRedirect(reverse('login'))


class ListBasket(ListView):
    model = Basket
    template_name = 'main/components/list_basket.html'
    context_object_name = 'basket'
        
    
@login_required
def delete(request, pk):
    product = get_object_or_404(Product, pk=pk, created_by=request.user)
    product.delete()
    
    return redirect('dashboard:index')

marketplace/project/products/templates/product/create_product.html
{% extends 'base.html' %}

{% block content %}

{% if request.user.is_authenticated %}
    <form method="post" action="" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}

        {% if form.errors or form.non_field_errors %}
            <div class="mb-3 p-6 bg-red-100 rounded-3">
                {% for field in form %}
                    {{ field.errors }}
                {% endfor %}

                {{ form.non_field_errors }}
            </div>
        {% endif %}

        <button type="submit" class="menu-title btn btn-success text-white">Добавить продукт</button>
    </form>
{% endif %}

{% endblock %}

marketplace/project/products/templates/product/product_detail.html
{% extends 'base.html' %}


{% block content %}
<div>
    <div class="d-flex row justify-content-around">
        <div class="col-5 p-2">
            <img src="{{ product.image.url }}" class="rounded w-100 h-auto">
        </div>
    
        <div class="col-6 p-6 bg-light rounded">
            <h1 class="mb-6">{{ product.name_prod }}</h1>
            <p class="text-gray"><strong>Цена: </strong>{{ product.price }}</p>
            <p class="text-gray"><strong>Продавец: </strong>{{ product.created_by }}</p>

            {% if product.description %}
                <p class="text-gray">
                    <strong>Описание: </strong><br>
                    {{ product.description }}
                </p>
            {% endif %}

            {% if request.user == product.created_by %}
                <div class="mt-6 p-6 bg-white rounded-3">
                    <p>Это ваш продукт!</p>

                    <a href="{% url 'product:edit' product.id %}" class="inline-block mt-6 px-6 py-3 text-lg font-semibold bg-success text-white rounded-3">Edit</a>
                    <a href="{% url 'product:delete' product.id %}" class="inline-block mt-6 px-6 py-3 text-lg font-semibold bg-danger text-white rounded-3">Delete</a>
                </div>
            {% else %}
                <div class="mt-4">                
                    <a href="{% url 'conversation:new' product.id %}" class="px-6 py-3 fw-bold text-white button-bg rounded">Написать продавцу</a>
                </div>
            {% endif %}
        </div>
    </div>
</div>

<div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
    <h2 class="mb-12 text-2xl text-center">Похожие объявления</h2>

    <div class="row">
        {% for product in related_products %}
            <div class="col-md-3 mb-3">
                <a href="{% url 'product:detail' product.id %}">
                    <div>
                        <img src="{{ product.image.url }}" class="rounded-top-xl" alt="" style="width: 100%; height:220px">
                    </div>

                    <div class="p-6 bg-white rounded-bottom-xl">
                        <h2 class="text-2xl">{{ product.name_prod  }}</h2>  
                        <p class="text-gray-500">Цена: {{ product.price }}</p>
                    </div>
                </a>
            </div>
        {% endfor %} 
    </div>
</div>
{% endblock %}

marketplace/project/products/templates/product/products.html
{% extends 'base.html' %}

{% block content %}
{% load static %}

<div class="row bg-gray-100">
    <div class="col-md-3">
        <form method="get" action="{% url 'product:products' %}">
            <input name="query" class="w-100 py-4 px-6 border rounded-2" type="text" value="{{ query }}" placeholder="Найти автомобиль, стул...">

            <button class="mt-2 py-3 px-5 text-lg bg-success text-white rounded-xl">Найти</button>
        </form>

        <hr class="my-6">

        <p class="fw-bold">Categories</p>

        <ul class="list-unstyled">
            {% for category in categories %}
                <li class="py-2 px-2 rounded{% if category.id == category_id %} bg-light{% endif %}">
                    <a href="{% url 'product:products' %}?query={{ query }}&category={{ category.id }}">{{ category.name_cat }}</a>
                </li>
            {% endfor %}
        </ul>

        <hr class="my-3">

        <p class="fw-bold">Очистить фильтр</p>

        <ul class="list-unstyled">
            <li>
                <a href="{% url 'product:products' %}" class="btn btn-custom mt-2 py-3 px-4 rounded text-white">Clear</a>
            </li>
        </ul>
    </div>

    <div class="col-md-9">
        <div class="row">
        {% for product in products %}
            <div class="col-md-4 mb-3">
                <a href="{% url 'product:detail' product.id %}">
                    <div>
                        <img src="{{ product.image.url }}" class="rounded-3 w-100 h-auto bg-white" alt="">
                    </div>

                    <div class="p-6 bg-white rounded-bottom-xl">
                        <h2 class="text-2xl">{{ product.name_prod }}</h2>  
                        <p class="text-gray-500">Цена: {{ product.price }}</p>
                    </div>
                </a>
            </div>
        {% endfor %} 
        </div>
    </div>
</div>

{% endblock %}