marketplace/project/core/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required
from core.views import MainPage, SignUp, Login, Logout

app_name = 'core'

urlpatterns = [
    path('', MainPage.as_view(), name='mainpage'),
    path('signup/', SignUp.as_view(), name='signup'),
    path('login/', Login.as_view(), name='login'),
    path('logout/', Logout.as_view(), name='logout'),
]

marketplace/project/dashboard/urls.py
from django.urls import path

from . import views

app_name = 'dashboard'

urlpatterns = [
    path('', views.index, name='index')
]

marketplace/project/products/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required
from products.views import CreateProduct, ProductDetail, delete, edit, products


app_name = 'product'

urlpatterns = [
    path('', products, name='products'),
    path('create_product/', login_required(CreateProduct.as_view()), name='create_product'),
    path('<int:pk>/', ProductDetail.as_view(), name='detail'),
    path('<int:pk>/delete/', delete, name='delete'),
    path('<int:pk>/edit/', edit, name='edit'),
]

marketplace/project/project/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('core.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('inbox/', include('conversation.urls')),
    path('products/', include('products.urls', namespace='products'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

marketplace/project/dashboard/models.py
from django.db import models

# Create your models here.

marketplace/project/dashboard/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required

from products.models import Product 


# Create your views here.
@login_required
def index(request):
    products = Product.objects.filter(created_by=request.user)
    
    return render(request, 'dashboard/index.html', {'products':products})

marketplace/project/dashboard/templates/dashboard/index.html
{% extends 'base.html' %}

{% block title %}Объявления{% endblock %}

{% block content %}

    <div class="mt-6 px-6 py-12 bg-gray-100 rounded-3">
        <h2 class="mb-6 text-center">Мои товары</h2>

        <div class="row">
            {% for product in products %}
                <div class="col-md-3 mb-3">
                    <a href="{% url 'product:detail' product.id %}">
                        <div>
                            <img src="{{ product.image.url }}" class="rounded-3 w-100 h-auto bg-white" alt="">
                        </div>

                        <div class="p-6 bg-white rounded-bottom-xl">
                            <h2 class="text-2xl">{{ product.name_prod }}</h2>  
                            <p class="text-gray-500">Цена: {{ product.price }}</p>
                        </div>
                    </a>
                </div>
            {% endfor %} 
        </div>
    </div>
{% endblock %}