marketplace/project/conversation/urls.py
from django.urls import path

from . import views

app_name = 'conversation'

urlpatterns = [
    path('', views.inbox, name='inbox'),
    path('<int:pk>/', views.detail, name='detail'),
    path('new/<int:product_pk>/', views.new_conversation, name='new'),
]

marketplace/project/core/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required
from core.views import MainPage, SignUp, Login, Logout

app_name = 'core'

urlpatterns = [
    path('', MainPage.as_view(), name='mainpage'),
    path('signup/', SignUp.as_view(), name='signup'),
    path('login/', Login.as_view(), name='login'),
    path('logout/', Logout.as_view(), name='logout'),
]

marketplace/project/dashboard/urls.py
from django.urls import path

from . import views

app_name = 'dashboard'

urlpatterns = [
    path('', views.index, name='index')
]

marketplace/project/products/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required
from products.views import CreateProduct, ProductDetail, delete, edit, products


app_name = 'product'

urlpatterns = [
    path('', products, name='products'),
    path('create_product/', login_required(CreateProduct.as_view()), name='create_product'),
    path('<int:pk>/', ProductDetail.as_view(), name='detail'),
    path('<int:pk>/delete/', delete, name='delete'),
    path('<int:pk>/edit/', edit, name='edit'),
]

marketplace/project/project/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('core.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('inbox/', include('conversation.urls')),
    path('products/', include('products.urls', namespace='products'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

marketplace/project/core/models.py
from django.db import models

# Create your models here.

marketplace/project/core/forms.py
from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django import forms
from django.contrib.auth.models import User


class LoginForm(AuthenticationForm):
    username = forms.CharField(max_length=15, required=True, widget = forms.TextInput(attrs={"class": "w-100 py-3 px-6 rounded-2"}))
    password = forms.CharField(max_length=15, required=True, widget = forms.PasswordInput(attrs={"class": "w-100 py-3 px-6 rounded-2"}))
    
    class Meta:
        model = User
        fields = ('username', 'password')
        widgets = {
            'username': forms.TextInput(attrs={"class": "w-100 py-3 px-3 rounded-2"}),
        }
        
class SignUpForm(UserCreationForm):
    password1 = forms.CharField(max_length=15, required=True, widget = forms.PasswordInput(attrs={"class": "w-100 py-3 px-6 rounded-2"}))
    password2 = forms.CharField(max_length=15, required=True, widget = forms.PasswordInput(attrs={"class": "w-100 py-3 px-6 rounded-2"}))
    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')
        widgets = {
            'username': forms.TextInput(attrs={"class": "w-100 py-3 px-3 rounded-2"}),
            'email': forms.EmailInput(attrs={"class": "w-100 py-3 px-3 rounded-2"}),
        }

marketplace/project/core/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse, reverse_lazy
from typing import Any
from django.contrib.auth.models import User
from django.contrib.auth.views import LoginView, LogoutView
from django.views.generic import CreateView, ListView, View

from products.models import Category, Product
from .forms import LoginForm, SignUpForm

from django.http import HttpRequest, HttpResponse, HttpResponseRedirect

# Create your views here.
class MainPage(ListView):
    model = Product
    template_name = 'main/main.html'
    context_object_name = 'products'
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # Добавьте ваш дополнительный параметр в контекст
        categories = Category.objects.all()
        context['categories'] = categories
        return context
    

class SignUp(CreateView):
    model = User
    form_class = SignUpForm
    template_name = 'auth/signup.html'
    success_url = reverse_lazy('core:login')
    
class Login(LoginView):
    form_class = LoginForm
    template_name = 'auth/login.html'
    next_page = 'core:mainpage'
    
    def get(self, request: HttpRequest, *args: str, **kwargs: Any) -> HttpResponse:
        if request.user.is_authenticated:
            return HttpResponseRedirect(reverse_lazy('mainpage'))
        else:
            return super().get(request, *args, **kwargs)
        
class Logout(LogoutView):
    next_page = 'core:mainpage'

marketplace/project/core/templates/components/css.html
{% load static %}
<link href="{% static 'core/css/datatables.bundle.css' %}" rel="stylesheet" type="text/css">
<link href="{% static 'core/css/vis-timeline.bundle.css' %}" rel="stylesheet" type="text/css">
<link href="{% static 'core/css/plugins.bundle.css' %}" rel="stylesheet" type="text/css">
<link href="{% static 'core/css/style.bundle.css' %}" rel="stylesheet" type="text/css">
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
<link rel="stylesheet" href="{% static 'core/css/style.css' %}">

marketplace/project/core/templates/components/footer.html
<div class="container">
    <footer class="footer">
        <div id="kt_app_footer" class="app-footer">
            <div class="container-fluid d-flex flex-column flex-md-row flex-center flex-md-stack py-3 ">
                <div class="text-dark order-2 order-md-1">
                    <span class="text-muted fw-semibold me-1">
                        <script>document.write(new Date().getFullYear())</script> ©
                    </span>
                    <a href="https://silkwaytransit.kz/" target="_blank"
                        class="text-gray-800 text-hover-primary">Developed by Amal</a>
                </div>
                <ul class="menu menu-gray-600 menu-hover-primary fw-semibold order-1">
                    <li class="menu-item"><a href="#" target="_blank" class="menu-link px-2">О нас</a></li>
                    <li class="menu-item"><a href="#" target="_blank" class="menu-link px-2">Поддержка</a></li>
                </ul>
            </div>
        </div>
    </footer>
</div>

marketplace/project/core/templates/components/logo.html
{% load static %}

<div>
    <a class="navbar-brand" href="{% url 'core:mainpage' %}">
        <img src="{% static 'core/img/logo.png' %}" alt="" width="150" height="50">
    </a>
</div>

marketplace/project/core/templates/components/menu.html
<nav>
    <div class="menu">
        
        <div class="menu-item">
            <a href="{% url 'product:create_product' %}" class="menu-link">
                <span class="menu-title btn btn-success text-white fs-4">Подать объявление</span>
            </a>
        </div>
        
        <div class="menu-item">
            <a href="/" class="menu-link">
                <span class="menu-title fs-4 text-white">Главная</span>
            </a>
        </div> 

        <div class="menu-item">
            <a href="{% url 'product:products' %}" class="menu-link">
                <span class="menu-title fs-4 text-white">Поиск</span>
            </a>
        </div> 
        
        {% if request.user.is_authenticated %}

            <div class="menu-item">
                <a href="{% url 'conversation:inbox' %}" class="menu-link">
                    <span class="menu-title fs-4 text-white">Сообщения</span>
                </a>
                <a href="{% url 'dashboard:index' %}" class="menu-link">
                    <span class="menu-title fs-4 text-white">Объявления</span>
                </a>
            </div>


            <div class="menu-item">
                <a href="{% url 'core:logout' %}" class="menu-link">
                    <span class="menu-title fs-4 text-white">Выйти</span>
                </a>
            </div>

        {% else %}

            <div class="menu-item" style="padding-right: 20px;">
                <a href="{% url 'core:login' %}" class="menu-link">
                    <span class="menu-title fs-4 text-white">Логин</span>
                </a>
            </div>

            <div class="menu-item" style="padding-right: 20px;">
                <a href="{% url 'core:signup' %}" class="menu-link">
                    <span class="menu-title fs-4 text-white">Регистрация</span>
                </a>
            </div>

        {% endif %}
    </div>
</nav>

marketplace/project/core/templates/components/meta.html
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>ShopM</title>

marketplace/project/core/templates/components/scripts.html
{% load static %}

<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js"
    integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r"
    crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js"
    integrity="sha384-BBtl+eGJRgqQAUMxJ7pMwbEyER4l1g+O15P+16Ep7Q9Q+zqX6gSbd85u4mG4QzX+"
    crossorigin="anonymous"></script>